apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.model.connectionSecretName }}
  namespace: {{ .Values.namespaces }}
  annotations:
    opendatahub.io/connection-type-ref: uri-v1
type: Opaque
stringData:
  URI: {{ .Values.model.storageUri | quote }}
