apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.model.name }}
  namespace: {{ .Values.namespaces.serving }}
spec:
  to:
    kind: Service
    name: {{ .Values.model.name }}-predictor
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
