apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.workbench.name }}-clone-repo
  namespace: {{ .Values.namespaces.serving }}
spec:
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: {{ .Values.workbench.name }}
      initContainers:
        - name: wait-for-workbench
          image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
          command: ["/bin/bash"]
          args:
            - -ec
            - |
              echo "Waiting for workbench pod..."
              while [ -z "$(oc get pods -n {{ .Values.namespaces.serving }} -l notebook-name={{ .Values.workbench.name }} -o jsonpath='{.items[0].status.phase}' 2>/dev/null | grep Running)" ]; do
                sleep 2
              done
              echo "Workbench pod is running."
      containers:
        - name: git-clone
          image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
          command: ["/bin/bash"]
          args:
            - -ec
            - |
              POD_NAME=$(oc get pods -n {{ .Values.namespaces.serving }} -l notebook-name={{ .Values.workbench.name }} -o jsonpath='{.items[0].metadata.name}')
              oc exec -n {{ .Values.namespaces.serving }} $POD_NAME -- bash -c "cd /opt/app-root/src && git clone {{ .Values.workbench.gitRepo.url }}"
      restartPolicy: Never
