apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: {{ .Values.workbench.name }}
  namespace: {{ .Values.namespaces }}
  annotations:
    notebooks.opendatahub.io/inject-oauth: "true"
    opendatahub.io/image-display-name: Standard Data Science
    notebooks.opendatahub.io/last-image-selection: 's2i-generic-data-science-notebook:2025.1'
    notebooks.opendatahub.io/last-image-version-git-commit-selection: '2e70684'
spec:
  template:
    spec:
      serviceAccountName: {{ .Values.workbench.name }}
      containers:
        - name: {{ .Values.workbench.name }}
          image: {{ .Values.workbench.image | quote }}
          imagePullPolicy: Always
          resources:
            requests:
              cpu: {{ .Values.workbench.resources.requests.cpu | quote }}
              memory: {{ .Values.workbench.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.workbench.resources.limits.cpu | quote }}
              memory: {{ .Values.workbench.resources.limits.memory | quote }}
          workingDir: /opt/app-root/src
          env:
            - name: NOTEBOOK_ARGS
              value: |-
                --ServerApp.port=8888
                --ServerApp.token=''
                --ServerApp.password=''
                --ServerApp.base_url=/notebook/{{ .Values.namespaces }}/{{ .Values.workbench.name }}
                --ServerApp.quit_button=False
                {{- if .Values.clusterdomainurl }}
                --ServerApp.tornado_settings={"user":"admin","hub_host":"https://rhods-dashboard-redhat-ods-applications.apps.{{ .Values.clusterdomainurl }}","hub_prefix":"/projects/{{ .Values.namespaces }}"}
                {{- end }}
            - name: JUPYTER_IMAGE
              value: {{ .Values.workbench.image | quote }}
          volumeMounts:
            - name: workbench-pvc
              mountPath: /opt/app-root/src
      volumes:
        - name: workbench-pvc
          persistentVolumeClaim:
            claimName: {{ .Values.workbench.pvc.name }}